import {
  BadgeCheck,
  BookOpenText,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  ChartNoAxesCombined,
  FileBarChart,
  FileChartColumn,
  FileCheck2,
  FilePenLine,
  FileSearch2,
  LayoutDashboard,
  ListOrdered,
  LogOut,
  MessageSquareMore,
  MessagesSquare,
  Mic,
  ScanSearch,
  ShieldCheck,
  Settings,
  Upload,
  UserCircle2,
  Users,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  LayoutDashboard,
  UserCircle2,
  Upload,
  ScanSearch,
  ShieldCheck,
  FileCheck2,
  BrainCircuit,
  BookOpenText,
  Mic,
  FileBarChart,
  Settings,
  LogOut,
  FilePenLine,
  FileSearch2,
  ListOrdered,
  BadgeCheck,
  MessagesSquare,
  FileChartColumn,
  Users,
  Building2,
  BriefcaseBusiness,
  ChartNoAxesCombined,
  MessageSquareMore,
}
